/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.cardapioController;
import controller.cardapioController;
import controller.cardapioController;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import model.cardapio;
import model.cardapioTableModel;
import model.cardapio;
import model.cardapioTableModel;
import controller.*;
import java.util.ArrayList;
import model.*;

/**
 *
 * @author Leonardo
 */
public class viewCardapio extends javax.swing.JFrame {

    /**
     * Creates new form teste
     */
    public viewCardapio() {
        initComponents();
        setLocationRelativeTo(null);
        this.atualizaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textDetalhes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        checkAtivo = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        buttonLimpar = new javax.swing.JButton();
        buttonBusca = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        buttonNovo = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        textBusca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();

        tabela = new javax.swing.JTable();
        buttonNovo1 = new javax.swing.JButton();
        buttonVoltar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPizzas = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaPizzaCardapio = new javax.swing.JTable();
        buttonAdicionarPizzaCardapio = new javax.swing.JButton();
        buttonRemoverPizzaCardapio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        textID.setEnabled(false);

        jLabel1.setText("Id");

        jLabel2.setText("Nome");

        jLabel3.setText("Detalhes");

        checkAtivo.setText("Ativo");

        jLabel4.setText("Status");

        buttonLimpar.setText("Limpar");
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        buttonBusca.setText("Pesquisar");
        buttonBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscaActionPerformed(evt);
            }
        });

        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonNovo.setText("Novo");
        buttonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovoActionPerformed(evt);
            }
        });

        buttonExcluir.setText("Excluir");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nome", "detalhes", "status"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        buttonNovo1.setText("Visualizar");
        buttonNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovo1ActionPerformed(evt);
            }
        });

        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        tabelaPizzas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabelaPizzas);

        tabelaPizzaCardapio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Descrição", "Status"
            }
        ));
        jScrollPane3.setViewportView(tabelaPizzaCardapio);

        buttonAdicionarPizzaCardapio.setText("Adicionar ao Cardapio");
        buttonAdicionarPizzaCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarPizzaCardapioActionPerformed(evt);
            }
        });

        buttonRemoverPizzaCardapio.setText("Remover");
        buttonRemoverPizzaCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverPizzaCardapioActionPerformed(evt);
            }
        });

        jLabel3.setText("Pizzas Disponíveis");

        jLabel5.setText("Pizzas do Cardápio Selecionado");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nome", "detalhes", "status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(textDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(checkAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 114, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(buttonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        int idCardapio=0;
        int idPizzaAdd=0;
        int idPizzaRemover=0;

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        cardapioController pc = new cardapioController();
        cardapio p = new cardapio();
        
        if(String.valueOf(textID.getText()).isEmpty()){
            JOptionPane.showMessageDialog(null, "ID não pode ser vazio");
            return;
        }
        p.setId(Integer.parseInt(textID.getText()));
        pc.excluir(p);
        this.limparTela();
        this.atualizaTabela();
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
      this.limparTela();
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void buttonBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscaActionPerformed
         cardapioController pc = new cardapioController();
            cardapio p = new cardapio();
            p.setNome(textBusca.getText());
            p.setStatus(false);
            if(checkAtivo.isSelected()){
                p.setStatus(true);
            }
            this.atualizarBusca(p);
    }//GEN-LAST:event_buttonBuscaActionPerformed

    private void buttonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovoActionPerformed
        cardapio p = new cardapio();
      
        if(textNome.equals("")){
            JOptionPane.showMessageDialog(null, "Verifique os dados Informados");
            return;
        }
        if(textDescricao.equals("")){
            JOptionPane.showMessageDialog(null, "Verifique os dados Informados");
            return;
        }
        cardapioController pc = new cardapioController();
        p.setNome(textNome.getText());;
        p.setStatus(true);
        p.setDetalhes(textDescricao.getText());
        pc.cadastrar(p);
        
        this.atualizaTabela();
        this.limparTela();
    }//GEN-LAST:event_buttonNovoActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        tabela.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent arg0) {
                    int linha = tabela.getSelectedRow();
                    textID.setText(tabela.getValueAt(linha, 0).toString());
                    textNome.setText(tabela.getValueAt(linha, 1).toString());
                    textDescricao.setText(tabela.getValueAt(linha, 2).toString());
                    String marcado = tabela.getValueAt(linha, 3).toString();
                    if(marcado=="true"){
                        checkAtivo.setSelected(true);
                    }
                    cardapioXpizza cp = new cardapioXpizza();
                    cp.setIdCardapio(Integer.parseInt(tabela.getValueAt(linha, 0).toString()));
                    carregaTabelaCardapioPizza(cp);
                    idCardapio = cp.getIdCardapio();
            }
        }); 
       tabelaPizzas.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent arg0) {
                    int linha = tabelaPizzas.getSelectedRow();
                    idPizzaAdd = Integer.parseInt(tabelaPizzas.getValueAt(linha, 0).toString()); 
            }
        });
       tabelaPizzaCardapio.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent arg0) {
                    int linha = tabelaPizzaCardapio.getSelectedRow();
                    idPizzaRemover = Integer.parseInt(tabelaPizzaCardapio.getValueAt(linha, 0).toString());                
            }
        });
    }//GEN-LAST:event_tabelaMouseClicked

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
            cardapio p = new cardapio();

            if(String.valueOf(textID.getText()).isEmpty()){
                JOptionPane.showMessageDialog(null, "Verifique os dados Informados");
                return;
            }
            if(String.valueOf(textNome.getText()).isEmpty()){
                JOptionPane.showMessageDialog(null, "Verifique os dados Informados");
                return;
            }
            if(String.valueOf(textDescricao.getText()).isEmpty()){
               JOptionPane.showMessageDialog(null, "Verifique os dados Informados");
               return;
            }
            cardapioController pc = new cardapioController();
            p.setId(Integer.parseInt(textID.getText()));
            p.setNome(textNome.getText());
            p.setStatus(false);
            p.setDetalhes(textDescricao.getText());
            if(checkAtivo.isSelected()){
                p.setStatus(true);
            }
            pc.alterar(p);
                       
            
            this.atualizaTabela();
            this.limparTela();
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovo1ActionPerformed
        cardapioXpizza cp = new cardapioXpizza();
        if(String.valueOf(textID.getText()).isEmpty()){
            JOptionPane.showMessageDialog(this, "Selecione um cardapio");
            return;
        }
        cp.setIdCardapio(Integer.parseInt(textID.getText()));
        cardapiosFinalizados viewFinalizados = new cardapiosFinalizados();
        viewFinalizados.setVisible(true);
        viewFinalizados.setCardapioNome(textNome.getText());
        viewFinalizados.carregarCardapio(cp);
    }//GEN-LAST:event_buttonNovo1ActionPerformed

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
       this.dispose();
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void checkAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkAtivoActionPerformed

    private void buttonAdicionarPizzaCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarPizzaCardapioActionPerformed
        if(idPizzaAdd <= 0){
            JOptionPane.showMessageDialog(null, "Escolha uma Pizza para adicionar");
            return;
        }
        if(idCardapio <=0){
            JOptionPane.showMessageDialog(null, "Escolha um Cardápio para adicionar");
            return;
        }
        cardapioXpizzaController cxc = new cardapioXpizzaController();
        cardapioXpizza cp = new cardapioXpizza();
        cp.setIdCardapio(idCardapio);
        cp.setIdPizza(idPizzaAdd);
        
        if(verificaExiste(cp)){
            cxc.cadastrar(cp); 
            carregaTabelaCardapioPizza(cp);
            idPizzaAdd=0;
        }else{
            JOptionPane.showMessageDialog(null, "Pizza já existe no cardápio selecionado");
        }
        
    }//GEN-LAST:event_buttonAdicionarPizzaCardapioActionPerformed

    private void buttonRemoverPizzaCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverPizzaCardapioActionPerformed
        if(idPizzaRemover <= 0){
            JOptionPane.showMessageDialog(null, "Escolha uma Pizza para remover");
            return;
        }
        if(idCardapio <=0){
            JOptionPane.showMessageDialog(null, "Escolha um Cardápio para adicionar");
            return;
        }
        
        cardapioXpizzaController cxc = new cardapioXpizzaController();
        cardapioXpizza cp = new cardapioXpizza();
        cp.setIdCardapio(idCardapio);
        cp.setIdPizza(idPizzaRemover);
        cxc.excluir(cp); 
        carregaTabelaCardapioPizza(cp);
        idPizzaAdd=0;
    }//GEN-LAST:event_buttonRemoverPizzaCardapioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCardapio().setVisible(true);
            }
        });
    }
    
    public void atualizaTabela(){
        tabela.setModel(new cardapioTableModel(new cardapioController().listarTodos()));
        tabelaPizzas.setModel(new pizzaTableModel(new pizzaController().listarTodos()));
    }
    
    public void carregaTabelaCardapioPizza(cardapioXpizza p){
        tabelaPizzaCardapio.setModel(new pizzaTableModel(new cardapioXpizzaController().buscar(p)));
    }
    
    public boolean verificaExiste(cardapioXpizza p){
        cardapioXpizzaController cxp = new cardapioXpizzaController();
        return cxp.verificaExiste(p);
    }
    
     public void atualizarBusca(cardapio p){
        tabela.setModel(new cardapioTableModel(new cardapioController().buscar(p)));
    }
     public void limparTela(){
        textID.setText("");
        textNome.setText("");
        textBusca.setText("");
        textDescricao.setText("");
        checkAtivo.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionarPizzaCardapio;
    private javax.swing.JButton buttonBusca;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonNovo;
    private javax.swing.JCheckBox checkAtivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabela;
    private javax.swing.JTable tabelaPizzaCardapio;
    private javax.swing.JTable tabelaPizzas;
    private javax.swing.JTextField textBusca;
    private javax.swing.JTextField textDescricao;

    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textBusca;
    private javax.swing.JTextField textDetalhes;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textNome;
    // End of variables declaration//GEN-END:variables
}
